apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: k8sprojectlearn
# Pod specs
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8sprojectlearn
    spec:
      containers:
        - name: first-app
          image: gcr.io/k8sprojectlearn/first-app:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: development
