kind: Service
apiVersion: v1
metadata:
  #Service name
  name: app-load-balancer
spec:
  selector:
    app: k8sprojectlearn
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
